

text="""The Cuban Missile Crisis, also known as the October Crisis (of 1962) (Spanish: Crisis de Octubre) in Cuba, the Caribbean Crisis (Russian: Карибский кризис, tr. Karibsky krizis, IPA: [kɐˈrʲipskʲɪj ˈkrʲizʲɪs]) in Russia, or the Missile Scare, was a 13-day (October 16 – October 29, 1962) confrontation between the United States and the Soviet Union, which escalated into an international crisis when American deployments of missiles in Italy and Turkey were matched by Soviet deployments of similar ballistic missiles in Cuba. Despite the short time frame, the Cuban Missile Crisis remains a defining moment in American national security and nuclear war preparation. The confrontation is often considered the closest the Cold War came to escalating into a full-scale conflict, nuclear war.[4]

In 1961, the US government put Jupiter nuclear missiles in Italy and Turkey. It had also trained a paramilitary force of Cuban exiles, which the CIA led in an attempt to invade Cuba and overthrow its government. Starting in November of that year, the US government engaged in a campaign of terrorism and sabotage in Cuba, referred to as the Cuban Project, which continued throughout the first half of the 1960s. The Soviet administration was concerned about a Cuban drift towards China, with which the Soviets had an increasingly fractious relationship. In response to these factors, Soviet First Secretary, Nikita Khrushchev, agreed with the Cuban Prime Minister, Fidel Castro, to place nuclear missiles on the island of Cuba to deter a future invasion. An agreement was reached during a secret meeting between Khrushchev and Castro in July 1962, and construction of a number of missile launch facilities started later that summer.

During the campaigning for the 1962 United States elections, the White House denied the charges for months and ignored the presence of Soviet missiles positioned approximately 90 mi (140 km) away from Florida. Later, the missile preparations were confirmed when a US Air Force U-2 spy plane produced clear photographic evidence of medium-range R-12 (NATO code name SS-4) and intermediate-range R-14 (NATO code name SS-5) ballistic missile facilities.

When this was reported to President John F. Kennedy, he then convened a meeting of the nine members of the National Security Council and five other key advisers, in a group that became known as the Executive Committee of the National Security Council (EXCOMM). During this meeting, President Kennedy was originally advised to carry out an air strike on Cuban soil in order to compromise Soviet missile supplies, followed by an invasion of the Cuban mainland. After careful consideration, President Kennedy chose a less aggressive course of action, in order to avoid a declaration of war. After consultation with EXCOMM, Kennedy ordered a naval "quarantine" on October 22 to prevent further missiles from reaching Cuba.[5] By using the term "quarantine", rather than "blockade" (an act of war by legal definition), the United States was able to avoid the implications of a state of war.[6] The US announced it would not permit offensive weapons to be delivered to Cuba and demanded that the weapons already in Cuba be dismantled and returned to the Soviet Union.

After several days of tense negotiations, an agreement was reached between Kennedy and Khrushchev: publicly, the Soviets would dismantle their offensive weapons in Cuba and return them to the Soviet Union, subject to United Nations verification, in exchange for a US public declaration and agreement to not invade Cuba again. Secretly, the United States agreed with the Soviets that it would dismantle all of the Jupiter MRBMs which had been deployed to Turkey against the Soviet Union. There has been debate on whether or not Italy was included in the agreement as well. While the Soviets dismantled their missiles, some Soviet bombers remained in Cuba, and the United States kept the naval quarantine in place until November 20, 1962.[6]

When all offensive missiles and the Ilyushin Il-28 light bombers had been withdrawn from Cuba, the blockade was formally ended on November 20. The negotiations between the United States and the Soviet Union pointed out the necessity of a quick, clear, and direct communication line between the two superpowers. As a result, the Moscow–Washington hotline was established. A series of agreements later reduced US–Soviet tensions for several years, until both parties eventually resumed expanding their nuclear arsenals.

The compromise embarrassed Khrushchev and the Soviet Union because the withdrawal of US missiles from Italy and Turkey was a secret deal between Kennedy and Khrushchev, and the Soviets were seen as retreating from circumstances that they had started. Khrushchev's fall from power two years later was in part because of the Soviet Politburo's embarrassment at both Khrushchev's eventual concessions to the US and his ineptitude in precipitating the crisis in the first place. According to Dobrynin, the top Soviet leadership took the Cuban outcome as "a blow to its prestige bordering on humiliation".[7][8]

Background
Cuba–Soviet relations
Main article: Escalante affair
In late 1961, Fidel Castro asked for more SA-2 anti-aircraft missiles from the Soviet Union. The request was not acted upon by the Soviet leadership. In the interval Fidel Castro began criticizing the Soviets for lack of "revolutionary boldness", and began talking to China about agreements for economic assistance. In March 1962, Fidel Castro ordered the ousting of Anibal Escalante and his pro-Moscow comrades from Cuba's Integrated Revolutionary Organizations. This affair alarmed the Soviet leadership as well as fears of a possible US invasion. In this crisis of international relations the Soviet Union sent more SA-2 anti-aircraft missiles in April as well as a regiment of regular Soviet troops.[9]

Timothy Naftali has contended that Escalante's dismissal was a motivating factor behind the Soviet decision to place nuclear missiles in Cuba in 1962. According to Naftali, Soviet foreign policy planners were concerned Castro's break with Escalante foreshadowed a Cuban drift toward China and sought to solidify the Soviet-Cuban relationship through the missile basing program.[10]

Cuba–US relations
Further information: Operation 40, Bay of Pigs Invasion, and Operation Mongoose

Image of plans for the Bay of Pigs Invasion
The Cuban government regarded US imperialism as the primary explanation for the island's structural weaknesses.[11] The US government had provided arms, money and its authority to the Batista dictatorship. The majority of the Cuban population had tired of the severe socioeconomic problems associated with the US domination of the country. The Cuban government was aware of the necessity of ending the turmoil and incongruities of US-dominated prerevolution Cuban society. It determined that the US government's demands, made as part of the hostile US reaction to Cuban government policy, were unacceptable.[11][12]

With the end of World War II and the start of the Cold War, the United States government sought to promote private enterprise as an instrument for advancing US strategic interests in the developing world.[13] It had grown concerned about the expansion of communism.

In December 1959, under the Eisenhower administration and less than twelve months after the Cuban Revolution, the Central Intelligence Agency (CIA) developed a plan for paramilitary action against Cuba. The CIA recruited operatives on the island to carry out terrorism and sabotage, kill civilians, and cause economic damage.[18] The John F. Kennedy administration was publicly embarrassed by the failed Bay of Pigs Invasion in April 1961. It had been launched at the initiative of Richard M. Bissell Jr. and approved by Kennedy, and used CIA-trained forces of Cuban exiles. Afterward, former President Eisenhower told Kennedy that "the failure of the Bay of Pigs will embolden the Soviets to do something that they would otherwise not do."[19]: 10 

Following the failed invasion, the US massively escalated its sponsorship of terrorism against Cuba. In late 1961, using the military and the Central Intelligence Agency, the US government engaged in an extensive campaign of state-sponsored terrorism against civilian and military targets on the island. The terrorist attacks killed significant numbers of civilians. The US armed, trained, funded and directed the terrorists, most of whom were Cuban expatriates. Terrorist attacks were planned at the direction and with the participation of US government employees and launched from US territory.[25] In January 1962, US Air Force General Edward Lansdale described the plans to overthrow the Cuban government in a top-secret report, addressed to Kennedy and officials involved with Operation Mongoose.[26][17] CIA agents or "pathfinders" from the Special Activities Division were to be infiltrated into Cuba to carry out sabotage and organization, including radio broadcasts.[27] In February 1962, the US launched an embargo against Cuba,[28] and Lansdale presented a 26-page, top-secret timetable for implementation of the overthrow of the Cuban government, mandating guerrilla operations to begin in August and September. "Open revolt and overthrow of the Communist regime" was hoped by the planners to occur in the first two weeks of October.[17]

The terrorism campaign and the threat of invasion were crucial factors in the Cuban government's decision to accept the placement of Soviet nuclear missiles on Cuban territory.[29][30][31][32] The US government was aware at the time, as reported to the president in a National Intelligence Estimate, that the invasion threat was a key reason for Cuban acceptance of the missiles.[33][34]

U.S. Soviet relations
Main article: Missile gap
See also: Berlin Crisis of 1961
When Kennedy ran for president in 1960, one of his key election issues was an alleged "missile gap" with the Soviets. In fact, the US at that time led the Soviets by a wide margin, which would only increase over time. In 1961, the Soviets had only four R-7 Semyorka intercontinental ballistic missiles (ICBMs). By October 1962, some intelligence estimates indicated a figure of 75.[35]

The US, on the other hand, had 170 ICBMs and was quickly building more. It also had eight George Washington- and Ethan Allen-class ballistic missile submarines, with the capability to launch 16 Polaris missiles, each with a range of 2,500 nautical miles (4,600 km). Khrushchev increased the perception of a missile gap when he loudly boasted to the world that the Soviets were building missiles "like sausages" but Soviet missiles' numbers and capabilities were nowhere close to his assertions. The Soviet Union had medium-range ballistic missiles in quantity, about 700 of them, but they were unreliable and inaccurate. The US had a considerable advantage in its total number of nuclear warheads (27,000 against 3,600) and in the technology required for their accurate delivery. The US also led in missile defensive capabilities, naval and air power; however, the Soviets held a two-to-one advantage in conventional ground forces, more pronounced in field guns and tanks, particularly in the European theatre.[35]

The Soviet First Secretary, Nikita Khrushchev, also had an impression of Kennedy as weak, which to him was confirmed by the President's response during the Berlin Crisis of 1961, particularly to the building of the Berlin Wall by East Germany to prevent its citizens from emigrating to the West.[36] The half-hearted nature of the Bay of Pigs invasion reinforced Khrushchev and his advisers impression that Kennedy was indecisive and, as one Soviet aide wrote, "too young, intellectual, not prepared well for decision making in crisis situations... too intelligent and too weak".[19] Speaking to Soviet officials in the aftermath of the crisis, Khrushchev asserted, "I know for certain that Kennedy doesn't have a strong background, nor, generally speaking, does he have the courage to stand up to a serious challenge." He also told his son Sergei that on Cuba, Kennedy "would make a fuss, make more of a fuss, and then agree".[37][page needed]

Prelude
Conception
In May 1962, Soviet First Secretary Nikita Khrushchev was persuaded by the idea of countering the US's growing lead in developing and deploying strategic missiles by placing Soviet intermediate-range nuclear missiles in Cuba, despite the misgivings of the Soviet Ambassador in Havana, Alexandr Ivanovich Alexeyev, who argued that Castro would not accept the deployment of the missiles.[38] Khrushchev faced a strategic situation in which the US was perceived to have a "splendid first strike" capability that put the Soviet Union at a huge disadvantage. In 1962, the Soviets had only 20 ICBMs capable of delivering nuclear warheads to the US from inside the Soviet Union.[39] The poor accuracy and reliability of the missiles raised serious doubts about their effectiveness. A newer, more reliable generation of ICBMs would become operational only after 1965.[39]

Therefore, Soviet nuclear capability in 1962 placed less emphasis on ICBMs than on medium and intermediate-range ballistic missiles (MRBMs and IRBMs). The missiles could hit American allies and most of Alaska from Soviet territory but not the contiguous United States. Graham Allison, the director of Harvard University's Belfer Center for Science and International Affairs, points out, "The Soviet Union could not right the nuclear imbalance by deploying new ICBMs on its own soil. In order to meet the threat it faced in 1962, 1963, and 1964, it had very few options. Moving existing nuclear weapons to locations from which they could reach American targets was one."[40]

A second reason that Soviet missiles were deployed to Cuba was that Khrushchev wanted to bring West Berlin, controlled by the American, British and French within Communist East Germany, into the Soviet orbit. The East Germans and Soviets considered western control over a portion of Berlin a grave threat to East Germany. Khrushchev made West Berlin the central battlefield of the Cold War. Khrushchev believed that if the US did nothing over the missile deployments in Cuba, he could muscle the West out of Berlin using said missiles as a deterrent to western countermeasures in Berlin. If the US tried to bargain with the Soviets after it became aware of the missiles, Khrushchev could demand trading the missiles for West Berlin. Since Berlin was strategically more important than Cuba, the trade would be a win for Khrushchev, as Kennedy recognized: "The advantage is, from Khrushchev's point of view, he takes a great chance but there are quite some rewards to it."[41]

Thirdly, from the perspective of the Soviet Union and of Cuba, it seemed that the United States wanted to increase its presence in Cuba. With actions including the attempt to expel Cuba from the Organization of American States,[42] placing economic sanctions on the nation, directly invading it in addition to conducting secret operations on containing communism and Cuba, it was assumed that America was trying to overrun Cuba. As a result, to try to prevent this, the USSR would place missiles in Cuba and neutralise the threat. This would ultimately serve to secure Cuba against attack and keep the country in the Socialist Bloc.[43]


Fifteen US-built PGM-19 Jupiter missiles, with the capability to strike Moscow with nuclear warheads, were deployed in Turkey in 1961.[citation needed]
Another major reason why Khrushchev planned to place missiles on Cuba undetected was to "level the playing field" with the evident American nuclear threat. America had the upper hand as they could launch from Turkey and destroy the USSR before they would have a chance to react. After the emplacement of nuclear missiles in Cuba, Khrushchev had finally established mutual assured destruction, meaning that if the United States decided to launch a nuclear strike against the Soviet Union, the latter would react by launching a retaliatory nuclear strike against the US.[44]

Finally, placing nuclear missiles on Cuba was a way for the USSR to show their support for Cuba and support the Cuban people who viewed the United States as a threatening force,[42] as the latter had become their ally after the Cuban Revolution of 1959. According to Khrushchev, the Soviet Union's motives were "aimed at allowing Cuba to live peacefully and develop as its people desire".[45]

Schlesinger, a historian and adviser to Kennedy, told National Public Radio in an interview on October 16, 2002, that Castro did not want the missiles, but Khrushchev pressured Castro to accept them. Castro was not completely happy with the idea, but the Cuban National Directorate of the Revolution accepted them, both to protect Cuba against US attack and to aid the Soviet Union.[46]: 272 

Soviet military deployments

The relative ranges of the Il-28, SS-4, and SS-5 based on Cuba in nautical miles (NM)
In early 1962, a group of Soviet military and missile construction specialists accompanied an agricultural delegation to Havana. They obtained a meeting with Cuban prime minister Fidel Castro. The Cuban leadership had a strong expectation that the US would invade Cuba again and enthusiastically approved the idea of installing nuclear missiles in Cuba. According to another source, Castro objected to the missiles' deployment as making him look like a Soviet puppet, but he was persuaded that missiles in Cuba would be an irritant to the US and help the interests of the entire socialist camp.[47] Also, the deployment would include short-range tactical weapons (with a range of 40 km, usable only against naval vessels) that would provide a "nuclear umbrella" for attacks upon the island.

By May, Khrushchev and Castro agreed to place strategic nuclear missiles secretly in Cuba. Like Castro, Khrushchev felt that a US invasion of Cuba was imminent and that to lose Cuba would do great harm to the communists, especially in Latin America. He said he wanted to confront the Americans "with more than words.... the logical answer was missiles".[48]: 29  The Soviets maintained their tight secrecy, writing their plans longhand, which were approved by Marshal of the Soviet Union Rodion Malinovsky on July 4 and Khrushchev on July 7.

From the very beginning, the Soviets' operation entailed elaborate denial and deception, known as "maskirovka". All the planning and preparation for transporting and deploying the missiles were carried out in the utmost secrecy, with only a very few told the exact nature of the mission. Even the troops detailed for the mission were given misdirection by being told that they were headed for a cold region and being outfitted with ski boots, fleece-lined parkas, and other winter equipment. The Soviet code-name was Operation Anadyr. The Anadyr River flows into the Bering Sea, and Anadyr is also the capital of Chukotsky District and a bomber base in the far eastern region. All the measures were meant to conceal the program from both internal and external audiences.[49]

Specialists in missile construction under the guise of "machine operators", "irrigation specialists", and "agricultural specialists" arrived in July.[49] A total of 43,000 foreign troops would ultimately be brought in.[50] Chief Marshal of Artillery Sergei Biryuzov, Head of the Soviet Rocket Forces, led a survey team that visited Cuba. He told Khrushchev that the missiles would be concealed and camouflaged by palm trees.[35]

As early as August 1962, the US suspected the Soviets of building missile facilities in Cuba. During that month, its intelligence services gathered information about sightings by ground observers of Soviet-built MiG-21 fighters and Il-28 light bombers. U-2 spy planes found S-75 Dvina (NATO designation SA-2) surface-to-air missile sites at eight different locations. CIA director John A. McCone was suspicious. Sending antiaircraft missiles into Cuba, he reasoned, "made sense only if Moscow intended to use them to shield a base for ballistic missiles aimed at the United States".[51] On August 10, he wrote a memo to Kennedy in which he guessed that the Soviets were preparing to introduce ballistic missiles into Cuba.[35] Che Guevara himself traveled to the Soviet Union on August 30, 1962 to sign off on the final agreement regarding the deployment of missiles in Cuba.[52] The visit was heavily monitored by the CIA as Guevara had gained more scruitiny by American intelligence. While in the Soviet Union Guevara argued with Khrushchev that the missile deal should be made public but Khrushchev insisted on total secrecy, and swore the Soviet Union's support if the Americans discovered the missiles. By the time Guevara arrived in Cuba the United States had already discovered the Soviet troops in Cuba via U-2 spy planes.[53]

With important Congressional elections scheduled for November, the crisis became enmeshed in American politics. On August 31, Senator Kenneth Keating (R-New York) warned on the Senate floor that the Soviet Union was "in all probability" constructing a missile base in Cuba. He charged the Kennedy administration with covering up a major threat to the US, thereby starting the crisis.[54] He may have received this initial "remarkably accurate" information from his friend, former congresswoman and ambassador Clare Boothe Luce, who in turn received it from Cuban exiles.[55] A later confirming source for Keating's information possibly was the West German ambassador to Cuba, who had received information from dissidents inside Cuba that Soviet troops had arrived in Cuba in early August and were seen working "in all probability on or near a missile base" and who passed this information to Keating on a trip to Washington in early October.[56] Air Force General Curtis LeMay presented a pre-invasion bombing plan to Kennedy in September, and spy flights and minor military harassment from US forces at Guantanamo Bay Naval Base were the subject of continual Cuban diplomatic complaints to the US government.[17]


Map created by American intelligence showing Surface-to-Air Missile activity in Cuba, September 5, 1962
The first consignment of Soviet R-12 missiles arrived on the night of September 8, followed by a second on September 16. The R-12 was a medium-range ballistic missile, capable of carrying a thermonuclear warhead.[57] It was a single-stage, road-transportable, surface-launched, storable liquid propellant fuelled missile that could deliver a megaton-class nuclear weapon.[citation needed] The Soviets were building nine sites—six for R-12 medium-range missiles (NATO designation SS-4 Sandal) with an effective range of 2,000 kilometres (1,200 mi) and three for R-14 intermediate-range ballistic missiles (NATO designation SS-5 Skean) with a maximum range of 4,500 kilometres (2,800 mi).[citation needed]

On October 7, Cuban President Osvaldo Dorticós Torrado spoke at the UN General Assembly: "If... we are attacked, we will defend ourselves. I repeat, we have sufficient means with which to defend ourselves; we have indeed our inevitable weapons, the weapons, which we would have preferred not to acquire, and which we do not wish to employ."[58] On October 10 in another Senate speech Sen. Keating reaffirmed his earlier warning of August 31 and stated that, "Construction has begun on at least a half dozen launching sites for intermediate range tactical missiles."[59]

The Cuban leadership was further upset when on September 20, the US Senate approved Joint Resolution 230, which expressed the US was determined "to prevent in Cuba the creation or use of an externally-supported military capability endangering the security of the United States".[60][61] On the same day, the US announced a major military exercise in the Caribbean, PHIBRIGLEX-62, which Cuba denounced as a deliberate provocation and proof that the US planned to invade Cuba.[61][62][unreliable source?]

The Soviet leadership believed, based on its perception of Kennedy's lack of confidence during the Bay of Pigs Invasion, that he would avoid confrontation and accept the missiles as a fait accompli.[19]: 1  On September 11, the Soviet Union publicly warned that a US attack on Cuba or on Soviet ships that were carrying supplies to the island would mean war.[17] The Soviets continued the Maskirovka program to conceal their actions in Cuba. They repeatedly denied that the weapons being brought into Cuba were offensive in nature. On September 7, Soviet Ambassador to the United States Anatoly Dobrynin assured United States Ambassador to the United Nations Adlai Stevenson that the Soviet Union was supplying only defensive weapons to Cuba. On September 11, the Telegraph Agency of the Soviet Union (TASS: Telegrafnoe Agentstvo Sovetskogo Soyuza) announced that the Soviet Union had no need or intention to introduce offensive nuclear missiles into Cuba. On October 13, Dobrynin was questioned by former Undersecretary of State Chester Bowles about whether the Soviets planned to put offensive weapons in Cuba. He denied any such plans.[61] On October 17, Soviet embassy official Georgy Bolshakov brought President Kennedy a personal message from Khrushchev reassuring him that "under no circumstances would surface-to-surface missiles be sent to Cuba."[61]: 494 

Missiles reported
The missiles in Cuba allowed the Soviets to effectively target most of the Continental US. The planned arsenal was forty launchers. The Cuban populace readily noticed the arrival and deployment of the missiles and hundreds of reports reached Miami. US intelligence received countless reports, many of dubious quality or even laughable, most of which could be dismissed as describing defensive missiles.[63][64][65]

Only five reports bothered the analysts. They described large trucks passing through towns at night that were carrying very long canvas-covered cylindrical objects that could not make turns through towns without backing up and maneuvering. Defensive missile transporters, it was believed, could make such turns without undue difficulty. The reports could not be satisfactorily dismissed.[66]


A U-2 reconnaissance photograph of Cuba, showing Soviet nuclear missiles, their transports and tents for fueling and maintenance
Aerial confirmation
The United States had been sending U-2 surveillance over Cuba since the failed Bay of Pigs Invasion.[67] The first issue that led to a pause in reconnaissance flights took place on August 30, when a U-2 operated by the US Air Force's Strategic Air Command flew over Sakhalin Island in the Soviet Far East by mistake. The Soviets lodged a protest and the US apologized. Nine days later, a Taiwanese-operated U-2[68][69] was lost over western China to an SA-2 surface-to-air missile (SAM). US officials were worried that one of the Cuban or Soviet SAMs in Cuba might shoot down a CIA U-2, initiating another international incident. In a meeting with members of the Committee on Overhead Reconnaissance (COMOR) on September 10, Secretary of State Dean Rusk and National Security Advisor McGeorge Bundy heavily restricted further U-2 flights over Cuban airspace. The resulting lack of coverage over the island for the next five weeks became known to historians as the "Photo Gap".[70] No significant U-2 coverage was achieved over the interior of the island. US officials attempted to use a Corona photo-reconnaissance satellite to obtain coverage over reported Soviet military deployments, but imagery acquired over western Cuba by a Corona KH-4 mission on October 1 was heavily covered by clouds and haze and failed to provide any usable intelligence.[71] At the end of September, Navy reconnaissance aircraft photographed the Soviet ship Kasimov, with large crates on its deck the size and shape of Il-28 jet bomber fuselages.[35]

In September 1962, analysts from the Defense Intelligence Agency (DIA) noticed that Cuban surface-to-air missile sites were arranged in a pattern similar to those used by the Soviet Union to protect its ICBM bases, leading DIA to lobby for the resumption of U-2 flights over the island.[72] Although in the past the flights had been conducted by the CIA, pressure from the Defense Department led to that authority being transferred to the Air Force.[35] Following the loss of a CIA U-2 over the Soviet Union in May 1960, it was thought that if another U-2 were shot down, an Air Force aircraft arguably being used for a legitimate military purpose would be easier to explain than a CIA flight.

When the reconnaissance missions were reauthorized on October 9, poor weather kept the planes from flying. The US first obtained U-2 photographic evidence of the missiles on October 14, when a U-2 flight piloted by Major Richard Heyser took 928 pictures on a path selected by DIA analysts, capturing images of what turned out to be an SS-4 construction site at San Cristóbal, Pinar del Río Province (now in Artemisa Province), in western Cuba.[73]


One of the first U-2 reconnaissance images of missile bases under construction shown to President Kennedy on the morning of October 16, 1962
President notified
On October 15, the CIA's National Photographic Interpretation Center (NPIC) reviewed the U-2 photographs and identified objects that they interpreted as medium range ballistic missiles. This identification was made, in part, on the strength of reporting provided by Oleg Penkovsky, a double agent in the GRU working for the CIA and MI6. Although he provided no direct reports of the Soviet missile deployments to Cuba, technical and doctrinal details of Soviet missile regiments that had been provided by Penkovsky in the months and years prior to the Crisis helped NPIC analysts correctly identify the missiles on U-2 imagery.[74]

That evening, the CIA notified the Department of State and at 8:30 pm EDT, Bundy chose to wait until the next morning to tell the President. McNamara was briefed at midnight. The next morning, Bundy met with Kennedy and showed him the U-2 photographs and briefed him on the CIA's analysis of the images.[75] At 6:30 pm EDT, Kennedy convened a meeting of the nine members of the National Security Council and five other key advisers,[76] in a group he formally named the Executive Committee of the National Security Council (EXCOMM) after the fact on October 22 by National Security Action Memorandum 196.[77] Without informing the members of EXCOMM, President Kennedy tape-recorded all of their proceedings, and Sheldon M. Stern, head of the Kennedy library transcribed some of them.[78][79]

On October 16, President Kennedy notified Attorney General Robert Kennedy that he was convinced the Soviets were placing missiles in Cuba and it was a legitimate threat. This made the threat of nuclear destruction by two world superpowers a reality. Robert Kennedy responded by contacting the Soviet Ambassador, Anatoly Dobrynin. Robert Kennedy expressed his "concern about what was happening" and Dobrynin "was instructed by Soviet Chairman Nikita S. Khrushchev to assure President Kennedy that there would be no ground-to-ground missiles or offensive weapons placed in Cuba". Khrushchev further assured Kennedy that the Soviet Union had no intention of "disrupting the relationship of our two countries" despite the photo evidence presented before President Kennedy.[80]"""

len(text)

import numpy as np
generator=icbe_llm_generator()

tokens=generator.tokenizer.encode(text)
tokens.shape

for i in range(100,200):
  text_small=text[0:(i*100)]
  tokens=generator.tokenizer.encode(text_small)
  print(tokens.shape, flush=True)
  results=generator.generate_simple(text_small, max_new_tokens = 1  )
  
#2744 is the most tokens I can put in before OOM  
#with attention 2 it feels a bit faster but the memory requirements didn't improve.
